roles: 'bps-test'
lanes: 5

# loadbalancer:
#     count: 2
#     scope: region
#     configs:
#         -
#             template: loadbalancer.config
#             web_servers:
#                 select_many:
#                     role: web
#                     scope: region
# queue:
#     count: 2
#     scope: zone


lbweb:
    count: 1
    scope: region

web:
    count: 10
    scope: lane
    configurations:
        -
            name: vhosts
            template: 'httpd-vhosts.conf'
            location: '/usr/local/apache2/conf/httpd-vhosts.conf'
            template_params:
                balancer: self
                balancer_members:
                    select_many:
                        role: app
                        # scope: region
                        chunk_size: 3
        -
            name: stop
            command: 'service httpd2 stop'
        -
            name: start
            command: 'service httpd2 start'
        -
            name: ips
            command: 'sudo -i ifconfig | grep "inet addr"'

app:
    count: 3
    scope: lane
    keypair: jgaigalas_key
    configurations:
        -
            name: database
            template: 'database.yml'
            location: '/bps/site/config/database.yml'
            template_params:
                server: self
                masterdb:
                    select_one: masterdb
                slavedb:
                    select_one:
                        role: slavedb
                        scope: region
        -
            name: stop
            command: 'su - bps -c "cd /bps/site; if [ -e tmp/pids/unicorn.pid ]; then <tmp/pids/unicorn.pid xargs kill; fi"'
        -
            name: start
            command: 'su - bps -c "cd /bps/site; bundle exec unicorn_rails -c config/unicorn.rb -E production -D"'


masterdb:
    count: 1
    scope: region
    db_name: 'bps'


slavedb:
    count: 2
    scope: zone


