roles: 'bps-test'
security_rules: 'bps'
zones:
    - a
    - b
    - c

settings:
    key1: "val1.1"

aliases:
    &start_http
        name: start
        command: 'service httpd2 start'


lbweb:
    count: 1
    scope: region

web:
    count: 1
    scope: zone
    configurations:
        -
            name: vhosts
            template: 'httpd-vhosts.conf'
            location: '/usr/local/apache2/conf/httpd-vhosts.conf'
            copy_as_user: 'root'
            template_params:
                balancer: self
                balancer_members:
                    select_many:
                        role: app
                        from: zone
                        chunk_size: 2

        - *start_http

        -
            name: ips
            command: 'sudo -i ifconfig | grep "inet addr"'
        -
            name: all
            command_set:
                - ips
                - start

app:
    count: 3
    scope: zone
    keypair: jgaigalas_key
    configurations:
        -
            name: database
            template: 'database.yml'
            location: '/bps/site/config/database.yml'
            template_params:
                server: self
                masterdb:
                    select_one: masterdb
                slavedb:
                    select_many:
                        role: slavedb
                        from: region
                        chunk_size: 4
        -
            name: stop
            command: 'su - bps -c "cd /bps/site; if [ -e tmp/pids/unicorn.pid ]; then <tmp/pids/unicorn.pid xargs kill; fi"'
        -
            name: start
            command: 'su - bps -c "cd /bps/site; bundle exec unicorn_rails -c config/unicorn.rb -E production -D"'


masterdb:
    count: 1
    scope: region
    db_name: 'bps'


slavedb:
    count: 2
    scope: zone

monitor:
    count: 1
    scope: zone
