roles: 'bps-test'
lanes: 1

# loadbalancer:
#     count: 2
#     scope: region
#     configs:
#         -
#             template: loadbalancer.config
#             web_servers:
#                 select_many:
#                     role: web
#                     scope: region
# queue:
#     count: 2
#     scope: zone


web:
    count: 2
    scope: lane
    keypair: jgaigalas_key
    configs:
        -
          template: '/etc/httpd/conf/proxy.conf'
          copy_to_location: '/etc/httpd/conf/proxy.conf'
          balancer: self
          balancer_members:
              select_many:
                  role: app
                  # scope: zone
                  # count: all
                  # distribute: all | split
                  # count: 12

        -
          template: 'vhosts'
          copy_to_location: '/etc/path/to/vhosts'
          server_aliases: ''
          community_name: 'turbotax'
          environment: 'perf'
          public_access: true
          force_nonstatic_ssl: true
          deploy_version: '1'
app:
    count: 4
    scope: lane
    keypair: jgaigalas_key
    configs:
        -
            template: 'database.yml'
            copy_to_location: '.'
            restart_command: 'cd /bps/site;kill `cat tmp/pids/unicorn.pid`;bundle exec unicorn_rails -c config/unicorn.rb -E production -D'
            server: self
            masterdb:
                select_one: masterdb
            slavedb:
                select_one:
                    role: slavedb
                    group: false # default false
                    # scope: zone

masterdb:
    count: 1
    scope: region
    db_name: 'bps'


slavedb:
    count: 1
    scope: zone


