roles: 'bps-test'
lanes: 1

# loadbalancer:
#     count: 2
#     scope: region
#     configs:
#         -
#             template: loadbalancer.config
#             web_servers:
#                 select_many:
#                     role: web
#                     scope: region
# queue:
#     count: 2
#     scope: zone


web:
    count: 2
    scope: lane
    keypair: jgaigalas_key
    configurations:
        -
          template: 'httpd-vhosts.conf'
          remote:
              location: '/usr/local/apache2/conf/httpd-vhosts.conf'
              stop: 'service httpd2 stop'
              start: 'service httpd2 start'
          template_params:
              balancer: self
              balancer_members:
                  select_many:
                      role: app
                      # scope: zone
                      chunk_size: 3

app:
    count: 4
    scope: lane
    keypair: jgaigalas_key
    configurations:
        -
            template: 'database.yml'
            remote:
                location: '/bps/site/config/database.yml'
                stop: 'su - bps -c "cd /bps/site; if [ -e tmp/pids/unicorn.pid ]; then <tmp/pids/unicorn.pid xargs kill; fi"'
                start: 'su - bps -c "cd /bps/site; bundle exec unicorn_rails -c config/unicorn.rb -E production -D"'
            template_params:
                server: self
                masterdb:
                    select_one: masterdb
                slavedb:
                    select_one:
                        role: slavedb
                        # scope: zone

masterdb:
    count: 1
    scope: region
    db_name: 'bps'


slavedb:
    count: 2
    scope: zone


