roles: 'lc'
lanes: 2

# loadbalancer:
#     count: 2
#     scope: region
#     configs:
#         -
#             template: loadbalancer.config
#             web_servers:
#                 select_many:
#                     role: web
#                     scope: region
# queue:
#     count: 2
#     scope: zone


web:
    count: 3
    scope: lane
    configs:
        -
          template: '/etc/httpd/conf/proxy.conf'
          copy_to_location: '/etc/httpd/conf/proxy.conf'
          balancer: self
          balancer_members:
              select_many:
                  role: app
                  # scope: zone
                  # count: all
                  # distribute: all | split
                  # count: 12

        -
          template: 'vhosts'
          copy_to_location: '/etc/path/to/vhosts'
          server_aliases: ''
          community_name: 'turbotax'
          environment: 'perf'
          public_access: true
          force_nonstatic_ssl: true
          deploy_version: '1'
app:
    count: 9
    scope: lane
    configs:
        -
            template: 'database.yml'
            copy_to_location: '.'
            copy_cap_command: 'control:move_database_yml'
            server: self
            masterdb:
                select_one: masterdb
            slavedb:
                select_one:
                    role: slavedb
                    group: true # default false
                    # scope: zone

masterdb:
    count: 1
    scope: region
    db_name: 'cia_prod'


slavedb:
    count: 4
    scope: zone


