{ "xmlns"=>"http://rds.amazonaws.com/admin/2009-10-16/", 
  "DescribeDBInstancesResult"=>{
    "DBInstances"=>{
      "DBInstance"=>[{"Engine"=>"mysql5.5", 
                      "PendingModifiedValues"=>{"DBInstanceClass"=>"db.m1.large"}, 
                      "BackupRetentionPeriod"=>"0", 
                      "DBInstanceStatus"=>"modifying", 
                      "DBParameterGroups"=>{"DBParameterGroup"=>{"ParameterApplyStatus"=>"pending-reboot", "DBParameterGroupName"=>"ttlc-mysql-5-5"}}, 
                      "DBInstanceIdentifier"=>"db1", 
                      "Endpoint"=>{"Port"=>"3306", "Address"=>"db1.cckovstulx2c.us-east-1.rds.amazonaws.com"}, 
                      "DBSecurityGroups"=>{"DBSecurityGroup"=>{"Status"=>"active", "DBSecurityGroupName"=>"default"}}, 
                      "PreferredBackupWindow"=>"07:30-08:00", 
                      "DBName"=>"cia_prod", 
                      "PreferredMaintenanceWindow"=>"fri:03:00-fri:03:30", 
                      "AvailabilityZone"=>"us-east-1c", 
                      "InstanceCreateTime"=>"2011-05-17T21:32:22.692Z", 
                      "AllocatedStorage"=>"300", 
                      "DBInstanceClass"=>"db.m1.small", 
                      "MasterUsername"=>"dbuser"}, 
                      
                     {"LatestRestorableTime"=>"2011-06-16T20:35:00Z", 
                      "Engine"=>"mysql5.5", 
                      "PendingModifiedValues"=>{"DBInstanceClass"=>"db.m1.large"}, 
                      "BackupRetentionPeriod"=>"7", 
                      "DBInstanceStatus"=>"modifying", 
                      "DBParameterGroups"=>{"DBParameterGroup"=>{"ParameterApplyStatus"=>"pending-reboot", "DBParameterGroupName"=>"ttlc-mysql-5-5"}}, 
                      "DBInstanceIdentifier"=>"masterdb", 
                      "Endpoint"=>{"Port"=>"3306", "Address"=>"masterdb.cckovstulx2c.us-east-1.rds.amazonaws.com"}, 
                      "DBSecurityGroups"=>{"DBSecurityGroup"=>{"Status"=>"active", "DBSecurityGroupName"=>"default"}}, 
                      "PreferredBackupWindow"=>"07:30-08:00", 
                      "DBName"=>"cia_prod", 
                      "PreferredMaintenanceWindow"=>"fri:03:00-fri:03:30", 
                      "AvailabilityZone"=>"us-east-1c", 
                      "InstanceCreateTime"=>"2011-05-11T21:57:15.999Z", 
                      "AllocatedStorage"=>"300", 
                      "DBInstanceClass"=>"db.m1.small", 
                      "MasterUsername"=>"dbuser"}, 
                      
                     {"Engine"=>"mysql5.5", 
                      "PendingModifiedValues"=>nil, 
                      "BackupRetentionPeriod"=>"0", 
                      "DBInstanceStatus"=>"available", 
                      "DBParameterGroups"=>{"DBParameterGroup"=>{"ParameterApplyStatus"=>"in-sync", "DBParameterGroupName"=>"ttlc-mysql-5-5"}}, 
                      "DBInstanceIdentifier"=>"sessions1", 
                      "Endpoint"=>{"Port"=>"3306", "Address"=>"sessions1.cckovstulx2c.us-east-1.rds.amazonaws.com"}, 
                      "DBSecurityGroups"=>{"DBSecurityGroup"=>{"Status"=>"active", "DBSecurityGroupName"=>"default"}}, 
                      "PreferredBackupWindow"=>"03:00-03:30", 
                      "DBName"=>"sessions", 
                      "PreferredMaintenanceWindow"=>"wed:08:30-wed:09:00", 
                      "AvailabilityZone"=>"us-east-1d", 
                      "InstanceCreateTime"=>"2011-05-11T18:56:43.988Z", 
                      "AllocatedStorage"=>"50", 
                      "DBInstanceClass"=>"db.m1.small", 
                      "MasterUsername"=>"dbuser"}
                    ]}
      }, 
    "ResponseMetadata"=>{"RequestId"=>"02e6b42c-9859-11e0-8d34-9bf543912f0b"}
  }